#!/usr/bin/env python3
"""
Quick script to help identify remaining English strings in React components
that need translation to Arabic.
"""

translations = {
    # Landing Page & General
    "Experience Grandland": "استكشف جراند لاند",
    "How It Feels Inside": "كيف يشعر من الداخل",
    "Luxury meets comfort": "الفخامة تلتقي الراحة",
    "Why Choose Opel?": "لماذا تختار أوبل؟",
    "Premium Design": "تصميم فاخر",
    "Cutting-edge aesthetics meets luxury comfort": "جمالية متقدمة تلتقي براحة فاخرة",
    "Electric Future": "المستقبل الكهربائي",
    "Eco-friendly performance without compromise": "أداء صديق للبيئة بدون تنازلات",
    "Advanced Tech": "تكنولوجيا متقدمة",
    "Latest AI and autonomous features": "أحدث ميزات الذكاء الاصطناعي والقيادة الذاتية",
    "What Our Customers Say": "ما يقول عملاؤنا",
    "Performance Highlights": "تسليط الضوء على الأداء",
    "Top Speed": "السرعة القصوى",
    "250+ km/h": "250+ كم/س",
    "0-100 km/h": "0-100 كم/س",
    "4.2s": "4.2 ثانية",
    "Electric Range": "مدى السير",
    "900km": "900 كم",
    "Power Output": "قوة الحصان",
    "400+ kW": "400+ كيلو وات",
    "Ready to Drive Excellence?": "هل أنت مستعد للقيادة بتميز؟",
    "Explore our complete collection and find your perfect Opel today.": "استكشف مجموعتنا الكاملة وجد أوبل المثالية لك اليوم.",
    "Browse Collection": "تصفح المجموعة",
    "Get in Touch": "تواصل معنا",
    "Have questions about our vehicles? Our team is ready to help you find the perfect Opel.": "هل لديك أسئلة حول سياراتنا؟ فريقنا جاهز لمساعدتك في العثور على أوبل المثالية.",
    "Call us now": "اتصل الآن",
    "Hours": "ساعات العمل",
    "Mon - Fri: 9AM - 6PM": "الاثنين - الجمعة: 9صباحاً - 6مساءً",
    
    # Cars Page
    "Browse Our Collection": "تصفح مجموعتنا",
    "Discover your perfect Opel": "اكتشف أوبل المثالية",
    "Search": "بحث",
    "Search cars...": "ابحث عن السيارات...",
    "Sort by": "ترتيب حسب",
    "Price: Low to High": "السعر: من الأقل إلى الأعلى",
    "Price: High to Low": "السعر: من الأعلى إلى الأقل",
    "Best Performance": "أفضل أداء",
    "Name: A to Z": "الاسم: من أ إلى ي",
    "Filters": "التصفية",
    "Vehicle Type": "نوع المركبة",
    "All Types": "جميع الأنواع",
    "Price Range": "نطاق السعر",
    "Showing": "عرض",
    "of": "من",
    "cars": "سيارات",
    "Clear all filters": "مسح جميع المرشحات",
    "View Details": "عرض التفاصيل",
    "No cars found matching your criteria.": "لم يتم العثور على سيارات تطابق معاييرك.",
    "Range": "مدى",
    
    # Car Modal
    "Starting from": "ابدأ من",
    "Model Year": "سنة الإصدار",
    "Power": "القوة",
    "Acceleration": "التسارع",
    "Transmission": "ناقل الحركة",
    "Seats": "المقاعد",
    "Premium Features": "الميزات المميزة",
    "Premium LED lighting system": "نظام إضاءة LED مميز",
    "Advanced AI driver assistance": "مساعد سائق ذكي متقدم",
    "Panoramic sunroof": "سقف بانوراما",
    "Premium sound system": "نظام صوت مميز",
    "Heated leather seats": "مقاعد جلدية مدفأة",
    "Wireless charging": "شحن لاسلكي",
    "Customize Your Vehicle": "تخصيص سيارتك",
    "Exterior Color": "لون الخارج",
    "Interior Package": "حزمة المقصورة",
    "Standard Fabric": "قماش قياسي",
    "Premium Leather": "جلد مميز",
    "Luxury Leather Plus": "جلد فاخر بلس",
    "Financing Options": "خيارات التمويل",
    "Loan Duration": "مدة القرض",
    "months": "أشهر",
    "2 years": "سنتان",
    "7 years": "7 سنوات",
    "Total Price": "السعر الإجمالي",
    "Monthly Payment": "الدفع الشهري",
    "Close": "إغلاق",
    "Add to Cart": "أضف إلى السلة",
    
    # Dashboard
    "Home": "الرئيسية",
    "Cars": "السيارات",
    "Logout": "تسجيل الخروج",
    "Midnight Black": "أسود في منتصف الليل",
    "Pearl White": "أبيض لؤلؤي",
    "Electric Blue": "أزرق كهربائي",
    "Metallic Silver": "فضي معدني",
}

for eng, ar in translations.items():
    print(f'"{eng}" -> "{ar}"')
